//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int RecordID { get; set; }
        public System.DateTime Date { get; set; }
        public string Venue { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<double> Payment { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<int> PaidBy { get; set; }
    
        public virtual MemberLogin MemberLogin { get; set; }
        public virtual MemberLogin MemberLogin1 { get; set; }
    }
}
